"""Event catalog, envelope, emit facade, and projection.

Sits directly above ``domain``; may not import ``adapters``, ``application``
or ``interfaces``.
"""

from northstack.events.catalog import (
    CURRENT_SCHEMA_VERSION,
    PAYLOAD_BY_KIND,
    PAYLOAD_MODELS,
    AnalysisCompleted,
    AnalysisRequested,
    ArtifactStored,
    BudgetUpdated,
    CellAdvanced,
    CellCompleted,
    CellCreated,
    CellFailed,
    CellStarted,
    ClaimRecorded,
    ContractAmended,
    ContractProposed,
    ContractValidated,
    EventKind,
    EventPayload,
    EvidenceRecorded,
    GraphAccepted,
    GraphProposed,
    OutcomeEmitted,
    PayloadBase,
    RecoveryTransition,
    RequestAccepted,
    RouteSelected,
    RunCreated,
    StatusChanged,
    VerificationCheck,
    WorkspaceSnapshot,
    parse_payload,
)
from northstack.events.envelope import EventEnvelope
from northstack.events.errors import LedgerCorruption, UnknownSchemaVersion
from northstack.events.stream import EventStream

__all__ = [
    "CURRENT_SCHEMA_VERSION",
    "PAYLOAD_BY_KIND",
    "PAYLOAD_MODELS",
    "AnalysisCompleted",
    "AnalysisRequested",
    "ArtifactStored",
    "BudgetUpdated",
    "CellAdvanced",
    "CellCompleted",
    "CellCreated",
    "CellFailed",
    "CellStarted",
    "ClaimRecorded",
    "ContractAmended",
    "ContractProposed",
    "ContractValidated",
    "EventEnvelope",
    "EventKind",
    "EventPayload",
    "EventStream",
    "EvidenceRecorded",
    "GraphAccepted",
    "GraphProposed",
    "LedgerCorruption",
    "OutcomeEmitted",
    "PayloadBase",
    "RecoveryTransition",
    "RequestAccepted",
    "RouteSelected",
    "RunCreated",
    "StatusChanged",
    "UnknownSchemaVersion",
    "VerificationCheck",
    "WorkspaceSnapshot",
    "parse_payload",
]
